-- CEPEF 2A | Central de Avisos | DDL | execute em projeto DIDÁTICO vazio
BEGIN;
CREATE TABLE IF NOT EXISTS public.setores (id_setor BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,nome VARCHAR(80) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS public.usuarios (id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,nome VARCHAR(100) NOT NULL,email VARCHAR(160) NOT NULL UNIQUE,id_setor BIGINT REFERENCES public.setores(id_setor));
CREATE TABLE IF NOT EXISTS public.categorias (id_categoria BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,nome VARCHAR(80) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS public.turmas (id_turma BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,nome VARCHAR(30) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS public.avisos (id_aviso BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,titulo VARCHAR(140) NOT NULL,descricao TEXT NOT NULL,data_evento DATE NOT NULL,id_usuario BIGINT NOT NULL REFERENCES public.usuarios(id_usuario),id_categoria BIGINT NOT NULL REFERENCES public.categorias(id_categoria));
-- Tabela associativa que resolve o relacionamento N:N
CREATE TABLE IF NOT EXISTS public.aviso_turma (id_aviso BIGINT NOT NULL REFERENCES public.avisos(id_aviso) ON DELETE CASCADE,id_turma BIGINT NOT NULL REFERENCES public.turmas(id_turma),PRIMARY KEY(id_aviso,id_turma));
COMMIT;
-- Exemplos para estudo, NÃO executar:
-- ALTER TABLE public.avisos ADD COLUMN local_evento VARCHAR(100);
-- DROP TABLE public.avisos; -- apaga estrutura e dados!
